/* ============================================================
   MundialBet Club 2026 — Plantillas (jugadores por selección)
   Jugadores reales de convocatorias recientes (2024-2026), 23 por equipo.
   P(dorsal, nombre, posición, titular?) · POR·DEF·MED·DEL · t:true = once inicial.
   Clave = nombre del equipo exactamente como en GROUP_STANDINGS.
   ============================================================ */
(function () {
  const P = (n, name, pos, t) => ({ n, name, pos, t: !!t });

  const PLAYERS = {
    'Brasil': [
      P(1,'Alisson','POR',1), P(12,'Bento','POR'), P(23,'Ederson','POR'),
      P(2,'Danilo','DEF',1), P(3,'Marquinhos','DEF',1), P(4,'Gabriel Magalhães','DEF',1), P(6,'Wendell','DEF',1),
      P(13,'Éder Militão','DEF'), P(14,'Beraldo','DEF'), P(22,'Vanderson','DEF'), P(16,'Abner','DEF'),
      P(5,'Casemiro','MED',1), P(8,'Bruno Guimarães','MED',1), P(15,'André','MED',1),
      P(17,'Gerson','MED'), P(18,'João Gomes','MED'), P(20,'Lucas Paquetá','MED'),
      P(10,'Rodrygo','DEL',1), P(7,'Vinícius Jr.','DEL',1), P(9,'Endrick','DEL',1),
      P(11,'Raphinha','DEL'), P(19,'Savinho','DEL'), P(21,'Estêvão','DEL'),
    ],
    'Argentina': [
      P(23,'Emiliano Martínez','POR',1), P(1,'Franco Armani','POR'), P(12,'Gerónimo Rulli','POR'),
      P(4,'Gonzalo Montiel','DEF',1), P(13,'Cristian Romero','DEF',1), P(6,'Germán Pezzella','DEF',1), P(3,'Nicolás Tagliafico','DEF',1),
      P(25,'Lisandro Martínez','DEF'), P(2,'Juan Foyth','DEF'), P(19,'Nicolás Otamendi','DEF'), P(26,'Nahuel Molina','DEF'),
      P(7,'Rodrigo De Paul','MED',1), P(5,'Leandro Paredes','MED',1), P(20,'Alexis Mac Allister','MED',1), P(24,'Enzo Fernández','MED',1),
      P(8,'Marcos Acuña','MED'), P(16,'Giovani Lo Celso','MED'),
      P(10,'Lionel Messi','DEL',1), P(22,'Lautaro Martínez','DEL',1), P(9,'Julián Álvarez','DEL',1),
      P(11,'Ángel Di María','DEL'), P(15,'Nicolás González','DEL'), P(21,'Paulo Dybala','DEL'),
    ],
    'Uruguay': [
      P(1,'Sergio Rochet','POR',1), P(12,'Santiago Mele','POR'), P(23,'Franco Israel','POR'),
      P(2,'José María Giménez','DEF',1), P(3,'Ronald Araújo','DEF',1), P(22,'Mathías Olivera','DEF',1), P(4,'Guillermo Varela','DEF',1),
      P(13,'Sebastián Cáceres','DEF'), P(19,'Sebastián Boselli','DEF'), P(16,'Mathías Viña','DEF'),
      P(6,'Rodrigo Bentancur','MED',1), P(5,'Manuel Ugarte','MED',1), P(15,'Federico Valverde','MED',1), P(10,'Giorgian de Arrascaeta','MED',1),
      P(7,'Nicolás de la Cruz','MED'), P(17,'Emiliano Martínez','MED'), P(8,'Facundo Pellistri','MED'),
      P(9,'Darwin Núñez','DEL',1), P(11,'Maxi Araújo','DEL',1), P(21,'Rodrigo Aguirre','DEL'),
      P(20,'Cristian Olivera','DEL'), P(18,'Brian Rodríguez','DEL'), P(14,'Federico Viñas','DEL'),
    ],
    'Panamá': [
      P(1,'Orlando Mosquera','POR',1), P(12,'Luis Mejía','POR'), P(22,'José Guerra','POR'),
      P(3,'Harold Cummings','DEF',1), P(13,'Eric Davis','DEF',1), P(5,'Andrés Andrade','DEF',1), P(2,'César Blackman','DEF',1),
      P(4,'Fidel Escobar','DEF'), P(23,'Michael Amir Murillo','DEF'), P(15,'Édgar Bárcenas','DEF'),
      P(20,'Aníbal Godoy','MED',1), P(6,'Cristian Martínez','MED',1), P(8,'Carlos Harvey','MED',1), P(17,'Adalberto Carrasquilla','MED',1),
      P(14,'Cristian Martínez','MED'), P(16,'Ydir Ovalle','MED'),
      P(9,'José Fajardo','DEL',1), P(7,'Ismael Díaz','DEL',1), P(19,'Cecilio Waterman','DEL',1),
      P(11,'Eric "Puma" Rodríguez','DEL'), P(10,'Edgardo Fariña','DEL'), P(18,'Tomás Rodríguez','DEL'), P(21,'Azarías Londoño','DEL'),
    ],
    'Francia': [
      P(1,'Mike Maignan','POR',1), P(16,'Brice Samba','POR'), P(23,'Lucas Chevalier','POR'),
      P(2,'Jules Koundé','DEF',1), P(4,'Dayot Upamecano','DEF',1), P(5,'William Saliba','DEF',1), P(22,'Theo Hernández','DEF',1),
      P(3,'Lucas Digne','DEF'), P(13,'Wesley Fofana','DEF'), P(18,'Ibrahima Konaté','DEF'), P(24,'Jonathan Clauss','DEF'),
      P(8,'Aurélien Tchouaméni','MED',1), P(13,'Eduardo Camavinga','MED',1), P(14,'Adrien Rabiot','MED',1),
      P(6,'Manu Koné','MED'), P(17,'Warren Zaïre-Emery','MED'),
      P(10,'Kylian Mbappé','DEL',1), P(11,'Ousmane Dembélé','DEL',1), P(9,'Marcus Thuram','DEL',1),
      P(7,'Bradley Barcola','DEL'), P(12,'Randal Kolo Muani','DEL'), P(20,'Michael Olise','DEL'), P(26,'Kingsley Coman','DEL'),
    ],
    'España': [
      P(23,'Unai Simón','POR',1), P(1,'David Raya','POR'), P(13,'Robert Sánchez','POR'),
      P(2,'Pedro Porro','DEF',1), P(4,'Robin Le Normand','DEF',1), P(14,'Aymeric Laporte','DEF',1), P(3,'Marc Cucurella','DEF',1),
      P(5,'Dani Vivian','DEF'), P(22,'Dani Carvajal','DEF'), P(24,'Pau Cubarsí','DEF'), P(20,'Álex Grimaldo','DEF'),
      P(16,'Rodri','MED',1), P(8,'Fabián Ruiz','MED',1), P(6,'Mikel Merino','MED',1), P(26,'Pedri','MED',1),
      P(12,'Martín Zubimendi','MED'), P(18,'Álex Baena','MED'),
      P(9,'Álvaro Morata','DEL',1), P(19,'Lamine Yamal','DEL',1), P(11,'Nico Williams','DEL',1),
      P(7,'Dani Olmo','DEL'), P(10,'Ferran Torres','DEL'), P(21,'Mikel Oyarzabal','DEL'),
    ],
    'Alemania': [
      P(1,'Manuel Neuer','POR',1), P(12,'Marc-André ter Stegen','POR'), P(22,'Oliver Baumann','POR'),
      P(2,'Antonio Rüdiger','DEF',1), P(4,'Jonathan Tah','DEF',1), P(3,'David Raum','DEF',1), P(23,'Nico Schlotterbeck','DEF',1),
      P(5,'Waldemar Anton','DEF'), P(15,'Maximilian Mittelstädt','DEF'), P(24,'Robin Koch','DEF'), P(16,'Benjamin Henrichs','DEF'),
      P(6,'Joshua Kimmich','MED',1), P(17,'Florian Wirtz','MED',1), P(21,'İlkay Gündoğan','MED',1),
      P(8,'Pascal Groß','MED'), P(18,'Aleksandar Pavlović','MED'), P(20,'Robert Andrich','MED'),
      P(10,'Jamal Musiala','DEL',1), P(7,'Kai Havertz','DEL',1), P(9,'Niclas Füllkrug','DEL',1),
      P(13,'Leroy Sané','DEL'), P(19,'Serge Gnabry','DEL'), P(14,'Maximilian Beier','DEL'),
    ],
    'Japón': [
      P(1,'Zion Suzuki','POR',1), P(12,'Daniel Schmidt','POR'), P(23,'Keisuke Osako','POR'),
      P(2,'Yukinari Sugawara','DEF',1), P(3,'Shogo Taniguchi','DEF',1), P(22,'Maya Yoshida','DEF',1), P(16,'Hiroki Ito','DEF',1),
      P(5,'Takehiro Tomiyasu','DEF'), P(4,'Ko Itakura','DEF'), P(26,'Yuto Nagatomo','DEF'), P(19,'Hiroki Sakai','DEF'),
      P(7,'Wataru Endo','MED',1), P(8,'Takefusa Kubo','MED',1), P(6,'Hidemasa Morita','MED',1), P(10,'Takumi Minamino','MED',1),
      P(17,'Ao Tanaka','MED'), P(13,'Hidemasa Morita','MED'),
      P(9,'Daizen Maeda','DEL',1), P(11,'Kaoru Mitoma','DEL',1), P(15,'Ayase Ueda','DEL',1),
      P(14,'Junya Ito','DEL'), P(20,'Keito Nakamura','DEL'), P(21,'Ritsu Doan','DEL'),
    ],
    'México': [
      P(1,'Guillermo Ochoa','POR',1), P(13,'Luis Malagón','POR'), P(12,'Carlos Acevedo','POR'),
      P(2,'Israel Reyes','DEF',1), P(3,'César Montes','DEF',1), P(15,'Johan Vásquez','DEF',1), P(23,'Jesús Gallardo','DEF',1),
      P(4,'Edson Álvarez','DEF'), P(5,'Jorge Sánchez','DEF'), P(6,'Gerardo Arteaga','DEF'), P(19,'Kevin Álvarez','DEF'),
      P(8,'Carlos Rodríguez','MED',1), P(16,'Luis Romo','MED',1), P(11,'Orbelín Pineda','MED',1),
      P(14,'Érick Sánchez','MED'), P(7,'Luis Chávez','MED'), P(17,'Roberto Alvarado','MED'),
      P(9,'Raúl Jiménez','DEL',1), P(22,'Hirving Lozano','DEL',1), P(10,'Alexis Vega','DEL',1),
      P(20,'Santiago Giménez','DEL'), P(21,'Henry Martín','DEL'), P(18,'Julián Quiñones','DEL'),
    ],
    'Estados Unidos': [
      P(1,'Matt Turner','POR',1), P(12,'Ethan Horvath','POR'), P(23,'Patrick Schulte','POR'),
      P(2,'Sergiño Dest','DEF',1), P(3,'Chris Richards','DEF',1), P(13,'Tim Ream','DEF',1), P(5,'Antonee Robinson','DEF',1),
      P(15,'Cameron Carter-Vickers','DEF'), P(22,'Joe Scally','DEF'), P(4,'Tyler Adams','MED'), P(26,'Miles Robinson','DEF'),
      P(8,'Weston McKennie','MED',1), P(6,'Yunus Musah','MED',1), P(14,'Luca de la Torre','MED',1),
      P(16,'Johnny Cardoso','MED'), P(19,'Malik Tillman','MED'),
      P(10,'Christian Pulisic','DEL',1), P(11,'Brenden Aaronson','DEL',1), P(9,'Folarin Balogun','DEL',1),
      P(7,'Giovanni Reyna','DEL'), P(20,'Ricardo Pepi','DEL'), P(21,'Tim Weah','DEL'), P(17,'Haji Wright','DEL'),
    ],
    'Canadá': [
      P(1,'Maxime Crépeau','POR',1), P(18,'Dayne St. Clair','POR'), P(12,'Milan Borjan','POR'),
      P(2,'Alistair Johnston','DEF',1), P(4,'Kamal Miller','DEF',1), P(5,'Steven Vitória','DEF',1), P(3,'Sam Adekugbe','DEF',1),
      P(15,'Moïse Bombito','DEF'), P(26,'Joel Waterman','DEF'), P(22,'Richie Laryea','DEF'),
      P(13,'Stephen Eustáquio','MED',1), P(6,'Ismaël Koné','MED',1), P(8,'Liam Fraser','MED',1),
      P(14,'Mathieu Choinière','MED'), P(20,'Jonathan Osorio','MED'),
      P(19,'Alphonso Davies','MED',1), P(7,'Liam Millar','DEL'),
      P(10,'Jonathan David','DEL',1), P(11,'Tajon Buchanan','DEL',1), P(9,'Cyle Larin','DEL',1),
      P(17,'Cyle Larin','DEL'), P(21,'Jacob Shaffelburg','DEL'), P(16,'Theo Bair','DEL'),
    ],
    'Islandia': [
      P(1,'Elías Rafn Ólafsson','POR',1), P(12,'Hákon Rafn Valdimarsson','POR'), P(13,'Ögmundur Kristinsson','POR'),
      P(2,'Birkir Már Sævarsson','DEF',1), P(5,'Sverrir Ingi Ingason','DEF',1), P(14,'Kári Árnason','DEF',1), P(18,'Hjörtur Hermannsson','DEF',1),
      P(3,'Guðmundur Þórarinsson','DEF'), P(4,'Alfons Sampsted','DEF'), P(15,'Daníel Leó Grétarsson','DEF'),
      P(8,'Mikael Anderson','MED',1), P(10,'Gylfi Sigurðsson','MED',1), P(7,'Jóhann Berg Guðmundsson','MED',1), P(17,'Arnór Sigurðsson','MED',1),
      P(6,'Hörður Magnússon','MED'), P(20,'Ísak Bergmann Jóhannesson','MED'), P(16,'Kristian Hlynsson','MED'),
      P(9,'Albert Guðmundsson','DEL',1), P(11,'Andri Guðjohnsen','DEL',1), P(21,'Sveinn Aron Guðjohnsen','DEL',1),
      P(19,'Orri Óskarsson','DEL'), P(22,'Stefán Teitur Þórðarson','DEL'), P(23,'Jón Dagur Þorsteinsson','DEL'),
    ],
    'Inglaterra': [
      P(1,'Jordan Pickford','POR',1), P(13,'Dean Henderson','POR'), P(23,'Aaron Ramsdale','POR'),
      P(2,'Kyle Walker','DEF',1), P(5,'John Stones','DEF',1), P(6,'Marc Guéhi','DEF',1), P(3,'Levi Colwill','DEF',1),
      P(12,'Kieran Trippier','DEF'), P(15,'Ezri Konsa','DEF'), P(2,'Trent Alexander-Arnold','DEF'), P(16,'Tino Livramento','DEF'),
      P(4,'Declan Rice','MED',1), P(8,'Jude Bellingham','MED',1), P(22,'Cole Palmer','MED',1),
      P(14,'Conor Gallagher','MED'), P(20,'Adam Wharton','MED'),
      P(9,'Harry Kane','DEL',1), P(7,'Bukayo Saka','DEL',1), P(11,'Phil Foden','DEL',1), P(10,'Jack Grealish','DEL',1),
      P(17,'Anthony Gordon','DEL'), P(18,'Ollie Watkins','DEL'), P(19,'Eberechi Eze','DEL'),
    ],
    'Países Bajos': [
      P(1,'Bart Verbruggen','POR',1), P(13,'Mark Flekken','POR'), P(23,'Nick Olij','POR'),
      P(2,'Denzel Dumfries','DEF',1), P(4,'Virgil van Dijk','DEF',1), P(3,'Matthijs de Ligt','DEF',1), P(5,'Nathan Aké','DEF',1),
      P(22,'Lutsharel Geertruida','DEF'), P(12,'Jorrel Hato','DEF'), P(15,'Micky van de Ven','DEF'), P(17,'Daley Blind','DEF'),
      P(8,'Tijjani Reijnders','MED',1), P(6,'Jerdy Schouten','MED',1), P(21,'Frenkie de Jong','MED',1),
      P(14,'Teun Koopmeiners','MED'), P(20,'Joey Veerman','MED'), P(16,'Mats Wieffer','MED'),
      P(7,'Xavi Simons','DEL',1), P(10,'Memphis Depay','DEL',1), P(9,'Cody Gakpo','DEL',1),
      P(18,'Donyell Malen','DEL'), P(11,'Brian Brobbey','DEL'), P(19,'Wout Weghorst','DEL'),
    ],
    'Bélgica': [
      P(1,'Koen Casteels','POR',1), P(12,'Matz Sels','POR'), P(16,'Thomas Kaminski','POR'),
      P(2,'Timothy Castagne','DEF',1), P(4,'Wout Faes','DEF',1), P(5,'Jan Vertonghen','DEF',1), P(3,'Arthur Theate','DEF',1),
      P(15,'Zeno Debast','DEF'), P(24,'Maxim De Cuyper','DEF'), P(21,'Timothy Castagne','DEF'),
      P(8,'Youri Tielemans','MED',1), P(6,'Amadou Onana','MED',1), P(7,'Kevin De Bruyne','MED',1),
      P(18,'Orel Mangala','MED'), P(20,'Hans Vanaken','MED'),
      P(10,'Leandro Trossard','DEL',1), P(11,'Jérémy Doku','DEL',1), P(9,'Romelu Lukaku','DEL',1), P(22,'Charles De Ketelaere','DEL',1),
      P(19,'Johan Bakayoko','DEL'), P(17,'Dodi Lukebakio','DEL'), P(14,'Loïs Openda','DEL'),
    ],
    'Suecia': [
      P(1,'Robin Olsen','POR',1), P(12,'Kristoffer Nordfeldt','POR'), P(23,'Viktor Johansson','POR'),
      P(2,'Emil Krafth','DEF',1), P(3,'Victor Lindelöf','DEF',1), P(4,'Isak Hien','DEF',1), P(5,'Ludwig Augustinsson','DEF',1),
      P(6,'Hjalmar Ekdal','DEF'), P(13,'Gabriel Gudmundsson','DEF'), P(15,'Daniel Svensson','DEF'),
      P(8,'Albin Ekdal','MED',1), P(10,'Emil Forsberg','MED',1), P(16,'Mattias Svanberg','MED',1),
      P(17,'Jens Cajuste','MED'), P(18,'Yasin Ayari','MED'),
      P(20,'Viktor Gyökeres','DEL',1), P(9,'Alexander Isak','DEL',1), P(11,'Dejan Kulusevski','DEL',1), P(7,'Anthony Elanga','DEL',1),
      P(14,'Viktor Claesson','DEL'), P(19,'Jesper Karlsson','DEL'), P(21,'Lucas Bergvall','MED'),
    ],
    'Portugal': [
      P(1,'Diogo Costa','POR',1), P(12,'José Sá','POR'), P(22,'Rui Patrício','POR'),
      P(2,'Diogo Dalot','DEF',1), P(3,'Pepe','DEF',1), P(4,'Rúben Dias','DEF',1), P(5,'Nuno Mendes','DEF',1),
      P(19,'Nélson Semedo','DEF'), P(13,'António Silva','DEF'), P(24,'Gonçalo Inácio','DEF'),
      P(8,'Bruno Fernandes','MED',1), P(6,'João Palhinha','MED',1), P(16,'Vitinha','MED',1), P(10,'Bernardo Silva','MED',1),
      P(14,'João Neves','MED'), P(18,'Rúben Neves','MED'),
      P(7,'Cristiano Ronaldo','DEL',1), P(17,'Rafael Leão','DEL',1), P(21,'Diogo Jota','DEL',1),
      P(11,'João Félix','DEL'), P(20,'Pedro Neto','DEL'), P(23,'Francisco Conceição','DEL'), P(9,'Gonçalo Ramos','DEL'),
    ],
    'Italia': [
      P(1,'Gianluigi Donnarumma','POR',1), P(12,'Guglielmo Vicario','POR'), P(23,'Michele Di Gregorio','POR'),
      P(2,'Giovanni Di Lorenzo','DEF',1), P(3,'Alessandro Bastoni','DEF',1), P(23,'Riccardo Calafiori','DEF',1), P(13,'Federico Dimarco','DEF',1),
      P(5,'Raoul Bellanova','DEF'), P(6,'Gianluca Mancini','DEF'), P(15,'Caleb Okoli','DEF'), P(24,'Andrea Cambiaso','DEF'),
      P(18,'Nicolò Barella','MED',1), P(8,'Jorginho','MED',1), P(16,'Bryan Cristante','MED',1), P(10,'Lorenzo Pellegrini','MED',1),
      P(7,'Davide Frattesi','MED'), P(4,'Michael Folorunsho','MED'),
      P(9,'Gianluca Scamacca','DEL',1), P(14,'Federico Chiesa','DEL',1), P(20,'Mateo Retegui','DEL',1),
      P(11,'Giacomo Raspadori','DEL'), P(17,'Moise Kean','DEL'), P(19,'Mateo Retegui','DEL'),
    ],
    'Suiza': [
      P(1,'Yann Sommer','POR',1), P(12,'Gregor Kobel','POR'), P(21,'Yvon Mvogo','POR'),
      P(2,'Silvan Widmer','DEF',1), P(5,'Manuel Akanji','DEF',1), P(22,'Fabian Schär','DEF',1), P(13,'Ricardo Rodríguez','DEF',1),
      P(4,'Nico Elvedi','DEF'), P(3,'Cédric Zesiger','DEF'), P(6,'Aurèle Amenda','DEF'),
      P(10,'Granit Xhaka','MED',1), P(8,'Remo Freuler','MED',1), P(15,'Djibril Sow','MED',1),
      P(23,'Xherdan Shaqiri','MED'), P(16,'Vincent Sierro','MED'), P(20,'Michel Aebischer','MED'),
      P(9,'Breel Embolo','DEL',1), P(7,'Ruben Vargas','DEL',1), P(18,'Zeki Amdouni','DEL',1),
      P(11,'Renato Steffen','DEL'), P(17,'Dan Ndoye','DEL'), P(14,'Kwadwo Duah','DEL'), P(19,'Cédric Itten','DEL'),
    ],
    'Arabia Saudita': [
      P(21,'Nawaf Al-Aqidi','POR',1), P(1,'Mohammed Al-Owais','POR'), P(22,'Mohammed Al-Rubaie','POR'),
      P(3,'Abdulelah Al-Amri','DEF',1), P(5,'Ali Al-Bulayhi','DEF',1), P(13,'Hassan Tambakti','DEF',1), P(2,'Saud Abdulhamid','DEF',1),
      P(4,'Ali Lajami','DEF'), P(6,'Hassan Kadesh','DEF'), P(12,'Jehad Thikri','DEF'), P(15,'Moteb Al-Harbi','DEF'),
      P(7,'Salem Al-Dawsari','MED',1), P(8,'Abdullah Al-Khaibari','MED',1), P(14,'Mohammed Kanno','MED',1), P(23,'Nasser Al-Dawsari','MED',1),
      P(16,'Musab Al-Juwayr','MED'), P(17,'Ziyad Al-Johani','MED'),
      P(9,'Firas Al-Buraikan','DEL',1), P(11,'Saleh Al-Shehri','DEL',1), P(10,'Khalid Al-Ghannam','DEL',1),
      P(18,'Abdullah Al-Hamdan','DEL'), P(19,'Ayman Yahya','DEL'), P(20,'Sultan Mandash','DEL'),
    ],
    'Australia': [
      P(1,'Mathew Ryan','POR',1), P(18,'Joe Gauci','POR'), P(12,'Paul Izzo','POR'),
      P(19,'Harry Souttar','DEF',1), P(20,'Kye Rowles','DEF',1), P(16,'Aziz Behich','DEF',1), P(2,'Milos Degenek','DEF',1),
      P(5,'Cameron Burgess','DEF'), P(3,'Nathaniel Atkinson','DEF'), P(4,'Kye Rowles','DEF'),
      P(13,'Aiden O’Neill','MED',1), P(22,'Jackson Irvine','MED',1), P(8,'Riley McGree','MED',1),
      P(23,'Connor Metcalfe','MED'), P(10,'Ajdin Hrustic','MED'), P(15,'Keanu Baccus','MED'),
      P(7,'Mathew Leckie','DEL',1), P(11,'Craig Goodwin','DEL',1), P(9,'Mitchell Duke','DEL',1),
      P(17,'Martin Boyle','DEL'), P(21,'Sammy Silvera','DEL'), P(14,'Kusini Yengi','DEL'), P(6,'Connor Metcalfe','MED'),
    ],
    'Perú': [
      P(1,'Pedro Gallese','POR',1), P(12,'Carlos Cáceda','POR'), P(23,'Diego Romero','POR'),
      P(2,'Luis Advíncula','DEF',1), P(5,'Carlos Zambrano','DEF',1), P(15,'Alexander Callens','DEF',1), P(3,'Miguel Trauco','DEF',1),
      P(4,'Anderson Santamaría','DEF'), P(6,'Marcos López','DEF'), P(17,'Luis Abram','DEF'),
      P(13,'Renato Tapia','MED',1), P(8,'Sergio Peña','MED',1), P(23,'Pedro Aquino','MED',1), P(18,'André Carrillo','MED',1),
      P(16,'Christian Cueva','MED'), P(14,'Pedro Aquino','MED'),
      P(9,'Gianluca Lapadula','DEL',1), P(20,'Edison Flores','DEL',1), P(11,'Bryan Reyna','DEL',1),
      P(7,'Paolo Guerrero','DEL'), P(21,'José Rivera','DEL'), P(10,'Christian Cueva','MED'), P(19,'Andy Polo','DEL'),
    ],
    'Corea del Sur': [
      P(1,'Kim Seung-gyu','POR',1), P(12,'Jo Hyeon-woo','POR'), P(23,'Song Bum-keun','POR'),
      P(2,'Kim Moon-hwan','DEF',1), P(4,'Kim Min-jae','DEF',1), P(20,'Kwon Kyung-won','DEF',1), P(3,'Kim Jin-su','DEF',1),
      P(15,'Jung Seung-hyun','DEF'), P(22,'Seol Young-woo','DEF'), P(5,'Kim Young-gwon','DEF'),
      P(6,'Hwang In-beom','MED',1), P(16,'Lee Jae-sung','MED',1), P(10,'Lee Kang-in','MED',1),
      P(8,'Park Yong-woo','MED'), P(13,'Jung Woo-young','MED'), P(17,'Hong Hyun-seok','MED'),
      P(7,'Son Heung-min','DEL',1), P(11,'Hwang Hee-chan','DEL',1), P(9,'Cho Gue-sung','DEL',1),
      P(18,'Oh Hyeon-gyu','DEL'), P(19,'Jeong Sang-bin','DEL'), P(14,'Bae Jun-ho','MED'), P(21,'Um Ji-sung','DEL'),
    ],
    'Marruecos': [
      P(1,'Yassine Bounou','POR',1), P(12,'Munir Mohamedi','POR'), P(23,'Yahya Jabrane','POR'),
      P(2,'Achraf Hakimi','DEF',1), P(5,'Nayef Aguerd','DEF',1), P(6,'Romain Saïss','DEF',1), P(3,'Noussair Mazraoui','DEF',1),
      P(20,'Achraf Dari','DEF'), P(18,'Jawad El Yamiq','DEF'), P(24,'Yusuf Sabaly','DEF'),
      P(4,'Sofyan Amrabat','MED',1), P(8,'Azzedine Ounahi','MED',1), P(15,'Selim Amallah','MED',1),
      P(13,'Bilal El Khannouss','MED'), P(16,'Amir Richardson','MED'),
      P(7,'Hakim Ziyech','DEL',1), P(19,'Youssef En-Nesyri','DEL',1), P(17,'Sofiane Boufal','DEL',1),
      P(11,'Abde Ezzalzouli','DEL'), P(9,'Ayoub El Kaabi','DEL'), P(10,'Brahim Díaz','DEL',1), P(21,'Eliesse Ben Seghir','DEL'),
    ],
    'Sudáfrica': [
      P(1,'Ronwen Williams','POR',1), P(16,'Ricardo Goss','POR'),
      P(2,'Khuliso Mudau','DEF',1), P(5,'Nkosinathi Sibisi','DEF',1), P(4,'Mothobi Mvala','DEF',1), P(3,'Aubrey Modiba','DEF',1),
      P(13,'Nyiko Mobbie','DEF'), P(12,'Thapelo Morena','DEF'),
      P(8,'Teboho Mokoena','MED',1), P(15,'Sphephelo Sithole','MED',1), P(10,'Themba Zwane','MED',1),
      P(6,'Bongani Zungu','MED'), P(18,'Yusuf Maart','MED'),
      P(21,'Percy Tau','DEL',1), P(20,'Lyle Foster','DEL',1), P(9,'Evidence Makgopa','DEL',1),
      P(7,'Oswin Appollis','DEL'), P(11,'Mihlali Mayambela','DEL'), P(19,'Iqraam Rayners','DEL'),
    ],
    'Chequia': [
      P(1,'Jindřich Staněk','POR',1), P(16,'Matěj Kovář','POR'),
      P(5,'Vladimír Coufal','DEF',1), P(15,'Tomáš Holeš','DEF',1), P(3,'Robin Hranáč','DEF',1), P(6,'Ladislav Krejčí','DEF',1),
      P(2,'David Doudera','DEF'), P(4,'David Zima','DEF'), P(22,'Martin Vitík','DEF'),
      P(8,'Tomáš Souček','MED',1), P(20,'Lukáš Provod','MED',1), P(13,'Antonín Barák','MED',1),
      P(18,'Petr Ševčík','MED'), P(14,'Michal Sadílek','MED'),
      P(10,'Patrik Schick','DEL',1), P(7,'Adam Hložek','DEL',1), P(9,'Tomáš Chorý','DEL',1),
      P(11,'Václav Černý','DEL'), P(19,'Mojmír Chytil','DEL'),
    ],
    'Bosnia y Herzegovina': [
      P(1,'Nikola Vasilj','POR',1), P(12,'Ibrahim Šehić','POR'),
      P(23,'Sead Kolašinac','DEF',1), P(2,'Amar Dedić','DEF',1), P(5,'Nikola Katić','DEF',1), P(4,'Adnan Kovačević','DEF',1),
      P(3,'Dennis Hadžikadunić','DEF'), P(6,'Sanjin Prcić','MED'),
      P(8,'Miralem Pjanić','MED',1), P(15,'Edin Višća','MED',1), P(20,'Benjamin Tahirović','MED',1),
      P(10,'Amar Begić','MED'), P(14,'Armin Gigović','MED'),
      P(11,'Edin Džeko','DEL',1), P(9,'Ermedin Demirović','DEL',1), P(17,'Haris Tabaković','DEL',1),
      P(7,'Smail Prevljak','DEL'), P(19,'Nemanja Bilbija','DEL'),
    ],
    'Catar': [
      P(22,'Meshaal Barsham','POR',1), P(1,'Saad Al-Sheeb','POR'),
      P(2,'Pedro Miguel','DEF',1), P(3,'Bassam Al-Rawi','DEF',1), P(15,'Tarek Salman','DEF',1), P(4,'Boualem Khoukhi','DEF',1),
      P(13,'Homam Ahmed','DEF'), P(16,'Musab Kheder','DEF'),
      P(8,'Karim Boudiaf','MED',1), P(12,'Abdulaziz Hatem','MED',1), P(23,'Mohammed Waad','MED',1),
      P(6,'Ahmed Fathi','MED'), P(14,'Ali Assadalla','MED'),
      P(10,'Hassan Al-Haydos','DEL',1), P(11,'Akram Afif','DEL',1), P(19,'Almoez Ali','DEL',1),
      P(7,'Yusuf Abdurisag','DEL'), P(17,'Ahmed Alaaeldin','DEL'),
    ],
    'Haití': [
      P(1,'Johny Placide','POR',1), P(16,'Josué Duverger','POR'),
      P(2,'Carlens Arcus','DEF',1), P(5,'Ricardo Adé','DEF',1), P(4,'Jean-Kévin Duverne','DEF',1), P(3,'Andrew Jean-Baptiste','DEF',1),
      P(13,'Garven Metusala','DEF'),
      P(8,'Danley Jean Jacques','MED',1), P(6,'Jems Geffrard','MED',1), P(15,'Leverton Pierre','MED',1),
      P(10,'Derrick Etienne','MED'), P(14,'Carl Sainté','MED'),
      P(9,'Frantzdy Pierrot','DEL',1), P(11,'Duckens Nazon','DEL',1), P(7,'Don Deedson Louicius','DEL',1),
      P(19,'Ruben Providence','DEL'), P(20,'Fabrice Picault','DEL'),
    ],
    'Escocia': [
      P(1,'Angus Gunn','POR',1), P(12,'Craig Gordon','POR'), P(23,'Zander Clark','POR'),
      P(3,'Andrew Robertson','DEF',1), P(6,'Kieran Tierney','DEF',1), P(5,'Jack Hendry','DEF',1), P(2,'Anthony Ralston','DEF',1),
      P(18,'Aaron Hickey','DEF'), P(4,'Scott McKenna','DEF'), P(14,'Ryan Porteous','DEF'), P(13,'Grant Hanley','DEF'),
      P(8,'Scott McTominay','MED',1), P(7,'John McGinn','MED',1), P(15,'Billy Gilmour','MED',1), P(16,'Callum McGregor','MED',1),
      P(22,'Stuart Armstrong','MED'), P(11,'Ryan Christie','MED'),
      P(9,'Che Adams','DEL',1), P(20,'Ben Doak','DEL',1), P(17,'Lyndon Dykes','DEL'),
      P(21,'Lawrence Shankland','DEL'), P(19,'Tommy Conway','DEL'),
    ],
    'Colombia': [
      P(1,'Camilo Vargas','POR',1), P(12,'David Ospina','POR'),
      P(4,'Santiago Arias','DEF',1), P(2,'Daniel Muñoz','DEF',1), P(13,'Yerry Mina','DEF',1), P(23,'Dávinson Sánchez','DEF',1),
      P(17,'Johan Mojica','DEF'), P(3,'Carlos Cuesta','DEF'),
      P(5,'Jefferson Lerma','MED',1), P(15,'Richard Ríos','MED',1), P(10,'James Rodríguez','MED',1),
      P(8,'Juan F. Quintero','MED'), P(16,'Mateus Uribe','MED'),
      P(7,'Luis Díaz','DEL',1), P(24,'Jhon Córdoba','DEL',1), P(11,'Jhon Arias','DEL',1),
      P(19,'Rafael Santos Borré','DEL'), P(9,'Jhon Durán','DEL'), P(14,'Luis Sinisterra','DEL'),
    ],
    'Croacia': [
      P(1,'Dominik Livaković','POR',1), P(12,'Ivica Ivušić','POR'),
      P(2,'Josip Stanišić','DEF',1), P(20,'Joško Gvardiol','DEF',1), P(5,'Josip Šutalo','DEF',1), P(22,'Josip Juranović','DEF',1),
      P(3,'Borna Sosa','DEF'), P(6,'Marin Pongračić','DEF'), P(19,'Borna Barišić','DEF'),
      P(10,'Luka Modrić','MED',1), P(8,'Mateo Kovačić','MED',1), P(11,'Marcelo Brozović','MED',1),
      P(7,'Lovro Majer','MED'), P(15,'Mario Pašalić','MED'), P(13,'Nikola Vlašić','MED'),
      P(9,'Andrej Kramarić','DEL',1), P(17,'Ante Budimir','DEL',1),
      P(16,'Bruno Petković','DEL'), P(14,'Igor Matanović','DEL'),
    ],
    'Ghana': [
      P(1,'Lawrence Ati-Zigi','POR',1), P(16,'Joseph Wollacott','POR'),
      P(2,'Alidu Seidu','DEF',1), P(5,'Mohammed Salisu','DEF',1), P(4,'Alexander Djiku','DEF',1), P(3,'Gideon Mensah','DEF',1),
      P(13,'Tariq Lamptey','DEF'), P(15,'Jerome Opoku','DEF'),
      P(8,'Thomas Partey','MED',1), P(20,'Mohammed Kudus','MED',1), P(6,'Elisha Owusu','MED',1),
      P(14,'Salis Abdul Samed','MED'), P(21,'Majeed Ashimeru','MED'),
      P(19,'Iñaki Williams','DEL',1), P(7,'Antoine Semenyo','DEL',1), P(9,'Jordan Ayew','DEL',1),
      P(11,'Kamaldeen Sulemana','DEL'), P(18,'Ernest Nuamah','DEL'), P(10,'Abdul Fatawu Issahaku','DEL'),
    ],
    'Senegal': [
      P(16,'Édouard Mendy','POR',1), P(1,'Seny Dieng','POR'),
      P(3,'Kalidou Koulibaly','DEF',1), P(22,'Abdou Diallo','DEF',1), P(4,'Moussa Niakhaté','DEF',1), P(2,'Krépin Diatta','DEF',1),
      P(12,'Ismail Jakobs','DEF'), P(21,'Antoine Mendy','DEF'),
      P(5,'Idrissa Gueye','MED',1), P(8,'Pape Matar Sarr','MED',1), P(6,'Lamine Camara','MED',1),
      P(15,'Pape Gueye','MED'), P(17,'Pathé Ciss','MED'),
      P(10,'Sadio Mané','DEL',1), P(9,'Nicolas Jackson','DEL',1), P(18,'Ismaïla Sarr','DEL',1),
      P(11,'Habib Diallo','DEL'), P(19,'Iliman Ndiaye','DEL'), P(20,'Boulaye Dia','DEL'),
    ],
    'Egipto': [
      P(1,'Mohamed El-Shenawy','POR',1), P(23,'Mohamed Sobhi','POR'),
      P(6,'Ahmed Hegazi','DEF',1), P(3,'Mohamed Abdelmonem','DEF',1), P(2,'Omar Kamal','DEF',1), P(13,'Ahmed Fattouh','DEF',1),
      P(5,'Mohamed Hany','DEF'), P(20,'Ramy Rabia','DEF'),
      P(17,'Mohamed Elneny','MED',1), P(8,'Emam Ashour','MED',1), P(7,'Mahmoud "Trezeguet" Hassan','MED',1),
      P(14,'Marwan Attia','MED'), P(19,'Ahmed Sayed "Zizo"','MED'),
      P(10,'Mohamed Salah','DEL',1), P(21,'Omar Marmoush','DEL',1), P(9,'Mostafa Mohamed','DEL',1),
      P(11,'Akram Tawfik','DEL'), P(18,'Ibrahim Adel','DEL'),
    ],
    'Irán': [
      P(1,'Alireza Beiranvand','POR',1), P(22,'Payam Niazmand','POR'),
      P(13,'Sadegh Moharrami','DEF',1), P(8,'Morteza Pouraliganji','DEF',1), P(19,'Majid Hosseini','DEF',1), P(3,'Milad Mohammadi','DEF',1),
      P(2,'Ramin Rezaeian','DEF'), P(5,'Aref Aghasi','DEF'),
      P(6,'Saeid Ezatolahi','MED',1), P(15,'Ahmad Nourollahi','MED',1), P(7,'Alireza Jahanbakhsh','MED',1),
      P(20,'Saman Ghoddos','MED'), P(17,'Mehdi Ghayedi','MED'),
      P(9,'Mehdi Taremi','DEL',1), P(10,'Sardar Azmoun','DEL',1),
      P(11,'Karim Ansarifard','DEL'), P(18,'Shahriyar Moghanlou','DEL'),
    ],
    'Noruega': [
      P(1,'Ørjan Nyland','POR',1), P(12,'Egil Selvik','POR'),
      P(5,'Kristoffer Ajer','DEF',1), P(3,'Leo Østigård','DEF',1), P(6,'Stian Gregersen','DEF',1), P(2,'Julian Ryerson','DEF',1),
      P(4,'David Møller Wolfe','DEF'), P(13,'Marcus Pedersen','DEF'),
      P(20,'Martin Ødegaard','MED',1), P(8,'Sander Berge','MED',1), P(18,'Fredrik Aursnes','MED',1),
      P(15,'Patrick Berg','MED'), P(14,'Morten Thorsby','MED'),
      P(9,'Erling Haaland','DEL',1), P(19,'Alexander Sørloth','DEL',1), P(7,'Antonio Nusa','DEL',1),
      P(11,'Jørgen Strand Larsen','DEL'), P(17,'Oscar Bobb','DEL'),
    ],
    'Argelia': [
      P(16,'Alexis Guendouz','POR',1), P(1,'Anthony Mandrea','POR'),
      P(6,'Aïssa Mandi','DEF',1), P(4,'Ramy Bensebaini','DEF',1), P(20,'Mohamed A. Tougai','DEF',1), P(2,'Youcef Atal','DEF',1),
      P(3,'Jaouen Hadjam','DEF'), P(5,'Ahmed Touba','DEF'),
      P(8,'Nabil Bentaleb','MED',1), P(13,'Houssem Aouar','MED',1), P(14,'Ismaël Bennacer','MED',1),
      P(15,'Adem Zorgane','MED'), P(17,'Ramiz Zerrouki','MED'),
      P(7,'Riyad Mahrez','DEL',1), P(11,'Mohamed Amoura','DEL',1), P(10,'Amine Gouiri','DEL',1),
      P(9,'Baghdad Bounedjah','DEL'), P(18,'Saïd Benrahma','DEL'),
    ],
    'Austria': [
      P(1,'Patrick Pentz','POR',1), P(23,'Niklas Hedl','POR'),
      P(2,'Stefan Posch','DEF',1), P(4,'Kevin Danso','DEF',1), P(5,'Philipp Lienhart','DEF',1), P(8,'David Alaba','DEF',1),
      P(15,'Maximilian Wöber','DEF'), P(3,'Phillipp Mwene','DEF'), P(16,'Flavius Daniliuc','DEF'),
      P(6,'Nicolas Seiwald','MED',1), P(10,'Konrad Laimer','MED',1), P(7,'Marcel Sabitzer','MED',1), P(19,'Christoph Baumgartner','MED',1),
      P(13,'Florian Grillitsch','MED'), P(14,'Romano Schmid','MED'),
      P(9,'Marko Arnautović','DEL',1), P(11,'Michael Gregoritsch','DEL'),
      P(17,'Patrick Wimmer','DEL'), P(20,'Maximilian Entrup','DEL'),
    ],
    'Ecuador': [
      P(1,'Hernán Galíndez','POR',1), P(12,'Alexander Domínguez','POR'),
      P(7,'Pervis Estupiñán','DEF',1), P(3,'Piero Hincapié','DEF',1), P(5,'Willian Pacho','DEF',1), P(17,'Ángelo Preciado','DEF',1),
      P(4,'Félix Torres','DEF'), P(2,'Joel Ordóñez','DEF'),
      P(23,'Moisés Caicedo','MED',1), P(20,'Alan Franco','MED',1), P(14,'Kendry Páez','MED',1),
      P(6,'Jhegson Méndez','MED'), P(16,'Patrik Mercado','MED'),
      P(13,'Enner Valencia','DEL',1), P(11,'Kevin Rodríguez','DEL',1), P(10,'Gonzalo Plata','DEL',1),
      P(19,'Jordy Caicedo','DEL'), P(9,'Leonardo Campana','DEL'), P(18,'Jeremy Sarmiento','DEL'),
    ],
    'Paraguay': [
      P(1,'Roberto Fernández','POR',1), P(12,'Carlos Coronel','POR'),
      P(2,'Gustavo Gómez','DEF',1), P(3,'Fabián Balbuena','DEF',1), P(22,'Omar Alderete','DEF',1), P(16,'Junior Alonso','DEF',1),
      P(4,'Juan Cáceres','DEF'), P(13,'Agustín Sández','DEF'),
      P(5,'Andrés Cubas','MED',1), P(15,'Mathías Villasanti','MED',1), P(8,'Diego Gómez','MED',1), P(10,'Miguel Almirón','MED',1),
      P(14,'Damián Bobadilla','MED'),
      P(9,'Antonio Sanabria','DEL',1), P(11,'Julio Enciso','DEL',1), P(7,'Ramón Sosa','DEL',1),
      P(19,'Ángel Romero','DEL'), P(20,'Alejandro Romero "Kaku"','DEL'),
    ],
    'Türkiye': [
      P(1,'Uğurcan Çakır','POR',1), P(12,'Altay Bayındır','POR'),
      P(2,'Zeki Çelik','DEF',1), P(3,'Merih Demiral','DEF',1), P(4,'Abdülkerim Bardakcı','DEF',1), P(20,'Ferdi Kadıoğlu','DEF',1),
      P(14,'Mert Müldür','DEF'), P(5,'Samet Akaydın','DEF'),
      P(8,'Hakan Çalhanoğlu','MED',1), P(6,'İsmail Yüksek','MED',1), P(15,'Orkun Kökçü','MED',1), P(10,'Arda Güler','MED',1),
      P(18,'Salih Özcan','MED'),
      P(19,'Kenan Yıldız','DEL',1), P(7,'Barış Alper Yılmaz','DEL',1), P(9,'Cenk Tosun','DEL',1),
      P(11,'Yusuf Yazıcı','DEL'), P(17,'Kerem Aktürkoğlu','DEL'),
    ],
    'Costa de Marfil': [
      P(1,'Yahia Fofana','POR',1), P(16,'Badra Ali Sangaré','POR'),
      P(4,'Odilon Kossounou','DEF',1), P(22,'Evan Ndicka','DEF',1), P(20,'Willy Boly','DEF',1), P(3,'Ghislain Konan','DEF',1),
      P(2,'Serge Aurier','DEF'), P(17,'Wilfried Singo','DEF'),
      P(8,'Franck Kessié','MED',1), P(5,'Ibrahim Sangaré','MED',1), P(6,'Seko Fofana','MED',1),
      P(13,'Jean Michaël Seri','MED'), P(15,'Lazare Amani','MED'),
      P(9,'Sébastien Haller','DEL',1), P(11,'Simon Adingra','DEL',1), P(19,'Nicolas Pépé','DEL',1),
      P(7,'Amad Diallo','DEL'), P(10,'Jonathan Bamba','DEL'), P(18,'Christian Kouamé','DEL'),
    ],
    'Túnez': [
      P(1,'Aymen Dahmen','POR',1), P(16,'Béchir Ben Saïd','POR'),
      P(2,'Mohamed Dräger','DEF',1), P(3,'Yassine Meriah','DEF',1), P(4,'Montassar Talbi','DEF',1), P(12,'Ali Abdi','DEF',1),
      P(20,'Wajdi Kechrida','DEF'), P(5,'Dylan Bronn','DEF'),
      P(13,'Aïssa Laïdouni','MED',1), P(7,'Ellyes Skhiri','MED',1), P(8,'Hamza Rafia','MED',1),
      P(6,'Ferjani Sassi','MED'), P(15,'Mohamed Ali Ben Romdhane','MED'),
      P(10,'Hannibal Mejbri','DEL',1), P(14,'Youssef Msakni','DEL',1), P(11,'Naïm Sliti','DEL',1),
      P(9,'Seifeddine Jaziri','DEL'), P(17,'Elias Saad','DEL'),
    ],
    'Nueva Zelanda': [
      P(1,'Max Crocombe','POR',1), P(12,'Alex Paulsen','POR'),
      P(2,'Tim Payne','DEF',1), P(5,'Michael Boxall','DEF',1), P(4,'Nando Pijnaker','DEF',1), P(3,'Liberato Cacace','DEF',1),
      P(13,'Finn Surman','DEF'), P(14,'Storm Roux','DEF'),
      P(6,'Joe Bell','MED',1), P(8,'Marko Stamenic','MED',1), P(15,'Matthew Garbett','MED',1),
      P(7,'Alex Rufer','MED'), P(17,'Cameron Howieson','MED'),
      P(9,'Chris Wood','DEL',1), P(11,'Ben Waine','DEL',1), P(10,'Kosta Barbarouses','DEL',1),
      P(19,'Eli Just','DEL'), P(18,'Sarpreet Singh','MED'),
    ],
    'Cabo Verde': [
      P(1,'Vozinha','POR',1), P(16,'Márcio Rosa','POR'),
      P(14,'Stopira','DEF',1), P(2,'Roberto "Pico" Lopes','DEF',1), P(4,'Logan Costa','DEF',1), P(3,'Diney','DEF',1),
      P(13,'Kenny Rocha','DEF'), P(15,'Steven Moreira','DEF'),
      P(8,'Jamiro Monteiro','MED',1), P(6,'Kevin Pina','MED',1), P(20,'Deroy Duarte','MED',1),
      P(18,'Laros Duarte','MED'), P(17,'Patrick Andrade','MED'),
      P(10,'Ryan Mendes','DEL',1), P(7,'Garry Rodrigues','DEL',1), P(11,'Bebé','DEL',1),
      P(9,'Gilson Benchimol','DEL'), P(19,'Dailon Livramento','DEL'), P(21,'Willy Semedo','DEL'),
    ],
    'Irak': [
      P(1,'Jalal Hassan','POR',1), P(22,'Ahmad Basil','POR'),
      P(2,'Hussein Ali','DEF',1), P(5,'Merchas Doski','DEF',1), P(4,'Rebin Sulaka','DEF',1), P(3,'Zaid Tahseen','DEF',1),
      P(13,'Akam Hashim','DEF'),
      P(8,'Amir Al-Ammari','MED',1), P(6,'Bashar Resan','MED',1), P(15,'Ibrahim Bayesh','MED',1), P(10,'Zidane Iqbal','MED',1),
      P(14,'Osama Rashid','MED'),
      P(9,'Aymen Hussein','DEL',1), P(11,'Ali Jasim','DEL',1), P(7,'Mohanad Ali','DEL',1),
      P(19,'Youssef Amyn','DEL'), P(18,'Mohammed Qasim','DEL'),
    ],
    'Jordania': [
      P(1,'Yazeed Abulaila','POR',1), P(12,'Abdullah Al-Fakhouri','POR'),
      P(5,'Yazan Al-Arab','DEF',1), P(3,'Abdallah Nasib','DEF',1), P(4,'Salem Al-Ajalin','DEF',1), P(2,'Ihsan Haddad','DEF',1),
      P(13,'Bara Marei','DEF'),
      P(6,'Noor Al-Rawabdeh','MED',1), P(8,'Nizar Al-Rashdan','MED',1), P(15,'Mahmoud Al-Mardi','MED',1),
      P(14,'Ehsan Haddad','MED'), P(16,'Yazan Al-Arab II','MED'),
      P(7,'Mousa Al-Tamari','DEL',1), P(9,'Yazan Al-Naimat','DEL',1), P(11,'Ali Olwan','DEL',1),
      P(19,'Mahmoud Al-Aradah','MED'), P(18,'Mohammad Abu Hasheesh','DEL'),
    ],
    'Congo RD': [
      P(1,'Lionel Mpasi','POR',1), P(16,'Timothy Fayulu','POR'),
      P(5,'Chancel Mbemba','DEF',1), P(3,'Arthur Masuaku','DEF',1), P(2,'Gédéon Kalulu','DEF',1), P(4,'Axel Tuanzebe','DEF',1),
      P(13,'Aaron Wan-Bissaka','DEF'),
      P(6,'Charles Pickel','MED',1), P(8,'Samuel Moutoussamy','MED',1), P(15,'Edo Kayembe','MED',1),
      P(14,'Ngal’ayel Mukau','MED'), P(17,'Brillant Bashile','MED'),
      P(9,'Cédric Bakambu','DEL',1), P(11,'Yoane Wissa','DEL',1), P(7,'Silas Katompa','DEL',1),
      P(19,'Fiston Mayele','DEL'), P(10,'Théo Bongonda','DEL'), P(18,'Meschack Elia','DEL'),
    ],
    'Uzbekistán': [
      P(1,'Utkir Yusupov','POR',1), P(12,'Abduvohid Nematov','POR'),
      P(2,'Abdukodir Khusanov','DEF',1), P(4,'Rustamjon Ashurmatov','DEF',1), P(3,'Farrukh Sayfiev','DEF',1), P(5,'Sherzod Nasrullaev','DEF',1),
      P(13,'Abdulla Abdullaev','DEF'),
      P(10,'Abbosbek Fayzullaev','MED',1), P(7,'Jaloliddin Masharipov','MED',1), P(6,'Otabek Shukurov','MED',1),
      P(15,'Jasurbek Yakhshiboev','MED'), P(14,'Khojimat Erkinov','MED'),
      P(9,'Eldor Shomurodov','DEL',1), P(11,'Igor Sergeev','DEL',1), P(17,'Khojiakbar Alijonov','DEL',1),
      P(19,'Oston Urunov','DEL'),
    ],
    'Curazao': [
      P(1,'Eloy Room','POR',1), P(12,'Kenneth Vermeer','POR'),
      P(2,'Cuco Martina','DEF',1), P(5,'Shurandy Sambo','DEF',1), P(4,'Armando Obispo','DEF',1), P(3,'Kevin Felida','DEF',1),
      P(13,'Roshon van Eijma','DEF'),
      P(6,'Leandro Bacuna','MED',1), P(8,'Juninho Bacuna','MED',1), P(10,'Tahith Chong','MED',1),
      P(15,'Kenji Gorré','MED'), P(14,'Jeremy Antonisse','MED'),
      P(9,'Gervane Kastaneer','DEL',1), P(11,'Sontje Hansen','DEL',1), P(7,'Jürgen Locadia','DEL',1),
      P(19,'Livano Comenencia','MED'), P(18,'Tyrese Noslin','DEL'),
    ],
  };

  if (window.MB) window.MB.PLAYERS = PLAYERS;
})();
